### ISSUE TITLE
3.A.1. Appointment of EC chair

### ISSUE THREAD

**Issue by yvonneng** [amiaopensource/amia-elections#1]
Suggest having chair of EC be an elected position, rather than appointed by Board, to maintain independence.

**Comment by dericed** [comment]
I suggest that this is out of scope with the purpose of the repository. This would be a recommendation to the ByLaws. The Bylaws state

>    Members of such committees, including chairperson, shall be appointed by and shall serve at the pleasure of the Executive Board.

And the Election Manual can not contradict this. OTOH the Chairs of the Committees of the Board are significant positions and there's been several comments here and the google doc about this status (recommendations for length in the position, influence of the membership in appointment). Personally I think it's worth discussion and it is a bylaws issue rather than an election manual issue.

**Comment by dericed** [comment]
closing for now, but tagging as `bylaws`
